### ISSUE TITLE
Unable to import _diptest

### ISSUE THREAD

**Issue by ghost** [alimuldal/diptest#3]
Hi @alimuldal,

I try to use your Python implementation of the dip test, but I encounter a problem...

Installation worked without any problem (on Python2.7 or Python3.4).

`import diptest` works fine, but `import diptest.diptest` fails with : `ImportError: No module named '_diptest'`

I created a symlink `/usr/local/lib/python3.4/dist-packages/diptest/_diptest.so` which links to `_diptest.cpython-34m.so` in same folder. Now there is no `ImportError` but an other one:
``` python
>>> import diptest.diptest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/diptest/diptest.py", line 2, in <module>
    import _diptest
  File "_diptest.pyx", line 1, in init diptest._diptest (diptest/_diptest.c:16641)
SystemError: Parent module '' not loaded, cannot perform relative import
```

Any idea what is going wrong? Thanks.

Kind regards,
Elodie.

**Comment by zimmermm** [comment]
For me the following solves the issue.
In diptest.py (line 2) it should be (at least for python 3.6): from diptest import _diptest

**Comment by ShikhaAgarwal** [comment]
For me after copying the _diptest.so file to the environment path variable solved the issue. (for python 2.7)
