### ISSUE TITLE
Unable to import diptest after installing git version

### ISSUE THREAD

**Issue by Erlaad** [alimuldal/diptest#6]
Hi, 
I have been trying to install and use your diptest module on Python 3.6.2. After running python setup.py, however, I could not call diptest() from diptest.diptest since "module diptest has no attribute diptest()".

After tinkering around, we found that by adding the "from diptest import diptest" file in the __init__.py file, it works correctly. The initial __init__.py file was empty after downloading and installing. I suspect a bug in the code.

I hope this helps.
Regards,
Stefano

**Comment by samnemo** [comment]
still getting import errors after your suggested fix; also, don't you mean  `__init__.py`  instead of `init.py` ?

**Comment by sportbilly23** [comment]
**\_\_init.py\_\_** file it's empty. To use diptest you must add this:

\_\_all\_\_ = ["dip", "diptest"]
from diptest.diptest import diptest
from diptest.diptest import dip

And in **diptest.py** you must change **import \_diptest** ...to... **from diptest import \_diptest**

All fine after this!

**Comment by alexhagen** [comment]
@sportbilly23 's method works.  I'll make a pull request for this to fix it, unless someone else has.
